plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'org.iesalandalus.programacion.biblioteca'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Configuración automatizada de JavaFX
javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.graphics', 'javafx.base' ]
}

dependencies {
    // Libreria Entrada (Archivos JAR locales en la carpeta 'libs')
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Driver de MySQL
    implementation 'mysql:mysql-connector-java:8.0.28'
}

// Clase principal del programa
application {
    mainClass = 'biblioteca.LanzadorAppBiblioteca'
}