name: Java Library CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar
        run: |
          # 1. Crear carpeta de salida
          mkdir -p bin
          
          # 2. Localizar el archivo JAR (buscamos en todo el proyecto)
          JAR_PATH=$(find . -name "*.jar" | head -n 1)
          echo "Librería encontrada en: $JAR_PATH"
          
          # 3. Localizar todos los .java
          find src -name "*.java" > fuentes.txt
          
          # 4. Compilar usando la ruta encontrada
          javac -d bin -cp "$JAR_PATH" @fuentes.txt
          echo "✅ ¡COMPILADO!"
