name: Java Library CI

on:
  push:
    branches: [ "main", "master", "trunk" ] # Se activa en cualquier rama principal
  pull_request:
    branches: [ "main", "master", "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Verificar carpeta de librerías
      run: |
        echo "Contenido de la carpeta libs:"
        ls -l libs/

    - name: Compilar Proyecto Java
      run: |
        mkdir -p bin
        # Buscamos todos los .java y compilamos usando el Classpath de la carpeta libs
        find . -name "*.java" > fuentes.txt
        javac -d bin -cp "libs/*" @fuentes.txt
        echo "✅ Compilación exitosa con librerías externas."
